In [5]:
import numpy as np
arr=np.array([1,2,3,4, 5])
print(arr)
print(type(arr))
print(arr.max())
print(arr.min())
print(arr.sum())
print(arr*2)
print(arr+10)
print(arr**2)



[1 2 3 4 5]
<class 'numpy.ndarray'>
5
1
15
[ 2  4  6  8 10]
[11 12 13 14 15]
[ 1  4  9 16 25]


In [6]:
pixel=np.array([255, 128, 64, 0])
normalized=pixel/255.0
print(normalized)

[1.         0.50196078 0.25098039 0.        ]


In [7]:
arr_2d=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ])
print(arr_2d.shape)

(3, 3)


In [8]:
arr_2d=np.array([
    [1,2,3,4],
    [4,5,6,7],
    [8,9,10,11],
    [12,13,14,15],
    [16,17,18,19]
])
print(arr_2d.shape)

(5, 4)


In [10]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[0])
print(arr[2])
print(arr[-1])
print(arr[1:5])
print(arr[:5])
print(arr[2:])

1
3
10
[2 3 4 5]
[1 2 3 4 5]
[ 3  4  5  6  7  8  9 10]


In [14]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
reshaped = arr.reshape(2, 5)
print(reshaped)
print(reshaped.shape)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [17]:
import pandas as pd
data={
    'medicine' : ['paracetamol','panadol','aspirin'],
    'riskscore' :['2','5','8'],
    'risklevel' :['low','medium','high']
}
df = pd.DataFrame(data)
print(df)
print(df['medicine'])
print(df['riskscore'])
print(df.iloc[0])
print(df.iloc[1])

      medicine riskscore risklevel
0  paracetamol         2       low
1      panadol         5    medium
2      aspirin         8      high
0    paracetamol
1        panadol
2        aspirin
Name: medicine, dtype: object
0    2
1    5
2    8
Name: riskscore, dtype: object
medicine     paracetamol
riskscore              2
risklevel            low
Name: 0, dtype: object
medicine     panadol
riskscore          5
risklevel     medium
Name: 1, dtype: object


In [22]:
import pandas as pd
data={
    'medicine' : ['paracetamol','panadol','aspirin'],
    'riskscore' :[2,5,8],
    'risklevel' :['low','medium','high']
}
df=pd.DataFrame(data)
high_risk=df[df['risklevel']=='high']
print(high_risk)

risky = df[df['riskscore'] > 5]
print(risky)

  medicine  riskscore risklevel
2  aspirin          8      high
  medicine  riskscore risklevel
2  aspirin          8      high
