In [1]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.dot(a,b))

32


In [2]:
import numpy as  np
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
result=np.matmul(A,B)
print(result)

[[19 22]
 [43 50]]


In [3]:
import torch
t=torch.tensor([1,2,3,4,5])
print(t)
print(t.shape)
print(t.dtype)

tensor([1, 2, 3, 4, 5])
torch.Size([5])
torch.int64


In [5]:
matrix=torch.tensor([[1,2,3],[4,5,6]])
print(matrix.shape)
print(matrix.dtype)
print(matrix*2)
print(matrix.sum())
print(matrix.mean(dtype=torch.float32))

torch.Size([2, 3])
torch.int64
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
tensor(21)
tensor(3.5000)


In [11]:
import torch
import torch.nn as nn
class Mediscannet(nn.Module):
   def __init__(self):
       super().__init__()
       self.layer1=nn.Linear(3,64)
       self.layer2=nn.Linear(64,32)
       self.layer3=nn.Linear(32,3)
       self.relu=nn.ReLU()
   def forward(self,x):
    x=self.relu(self.layer1(x))
    x=self.relu(self.layer2(x))
    x=self.layer3(x)
    return x

model=Mediscannet()
print(model)



Mediscannet(
  (layer1): Linear(in_features=3, out_features=64, bias=True)
  (layer2): Linear(in_features=64, out_features=32, bias=True)
  (layer3): Linear(in_features=32, out_features=3, bias=True)
  (relu): ReLU()
)
